# Use root/example as user/password credentials
version: '3.1'


volumes:
    mongodata:
        external: false

services:

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DB_USER
      MONGO_INITDB_ROOT_PASSWORD: $DB_PASS
    volumes:
        - mongodata:/tmp/mongo
    ports:
        - 27017:27017

  redis:
    image: redis:alpine
    restart: always
